package basic;
import com.ftn.sbnz.model.users.Injury;
import com.ftn.sbnz.model.Filters;
import com.ftn.sbnz.model.RecommendedArticleDTO;
import com.ftn.sbnz.model.articles.Article;
import com.ftn.sbnz.model.articles.GrassFootbalShoe;
import com.ftn.sbnz.model.sport.Sport;
import com.ftn.sbnz.model.sport.SportLevel;
import com.ftn.sbnz.model.sport.SportTenisField;
import com.ftn.sbnz.model.articles.Ball;
import com.ftn.sbnz.model.articles.BallType;
import com.ftn.sbnz.model.articles.GearTypeFootball;
import com.ftn.sbnz.model.articles.FootballGear;
import com.ftn.sbnz.model.articles.FootbalShoeNoCrampons;
import com.ftn.sbnz.model.articles.FootbalShoeCrampons;
import com.ftn.sbnz.model.sport.SportFootballType;
import com.ftn.sbnz.model.sport.SportLevel;
import com.ftn.sbnz.model.sport.SportFootballPlayer;

import java.util.Set;
import java.util.List;

global Set<RecommendedArticleDTO> recommendations;
global List<Injury> injuries;


rule "Recommend soccer balls"
salience 100
when
    $filters: Filters(sport == Sport.Fudbal, (age >= 12 || age == null || age == 0), level == null, typeOfFootball == null)
    $article: Article()
    $ball: Ball() from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Ball");
    recommendedArticle.setPathToImage($article.getPathToImage());
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Recommend soccer balls for kids"
salience 100
when
    $filters: Filters(sport == Sport.Fudbal, age < 12)
    $article: Article()
    $ball: Ball(type == BallType.Decija) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Ball");
    recommendedArticle.setPathToImage($article.getPathToImage());
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "The chosen option is small football, we recommend sneakers without crampons"
salience 100
when
    $filters: Filters(sport == Sport.Fudbal, typeOfFootball == SportFootballType.Mali)
    $article: Article()
    $shoe: FootbalShoeNoCrampons() from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Shoes");
    recommendedArticle.setPathToImage($article.getPathToImage());
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Futsal, over 12 years old, Recommend him 4 soccer balls with weights"
salience 100
when
    $filters: Filters(sport == Sport.Fudbal, age > 12, typeOfFootball == SportFootballType.Mali)
    $article: Article()
    $ball: Ball(type == BallType.CetiriSaTegom) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Ball");
    recommendedArticle.setPathToImage($article.getPathToImage());
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Recreational, amateur balls recommended"
salience 100
when
    $filters: Filters(sport == Sport.Fudbal, (age >= 12 || age == null || age == 0), level == SportLevel.Rekreativac)
    $article: Article()
    $ball: Ball(type == BallType.Amaterska) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Ball");
    recommendedArticle.setPathToImage($article.getPathToImage());
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Amateur, recommend amateur and training balls"
salience 100
when
    $filters: Filters(sport == Sport.Fudbal, (age >= 12 || age == null || age == 0), level == SportLevel.Amater)
    $article: Article()
    $ball: Ball(type == BallType.Amaterska || type == BallType.Trening) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Ball");
    recommendedArticle.setPathToImage($article.getPathToImage());
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Professional, recommend pro and training balls"
salience 100
when
    $filters: Filters(sport == Sport.Fudbal, (age >= 12 || age == null || age == 0), level == SportLevel.Pro)
    $article: Article()
    $ball: Ball(type == BallType.Profesionalna || type == BallType.Trening) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Ball");
    recommendedArticle.setPathToImage($article.getPathToImage());
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Injury of the ankle joint, offer a shin protector with an ankle protector"
salience 100
when
    $filters: Filters(sport == Sport.Fudbal, $selectedInjuries: injuries)
    Injury(name == "Povreda skocnog zgloba", $injuryId: id) from injuries
    eval($selectedInjuries.contains($injuryId))
    $article: Article()
    $shinProtector: FootballGear(type == GearTypeFootball.KostobranSaStitnikomZaSkocniZglob) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Shin protector");
    recommendedArticle.setPathToImage($article.getPathToImage());
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "There is no injury to the ankle joint, offer a shin protector without a guard"
salience 100
when
    $filters: Filters(sport == Sport.Fudbal, $selectedInjuries: injuries)
    Injury(name == "Povreda skocnog zgloba", $injuryId: id) from injuries
    eval(!$selectedInjuries.contains($injuryId))
    $article: Article()
    $shinProtector: FootballGear(type == GearTypeFootball.KostobranBezStitnika) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Shin protector");
    recommendedArticle.setPathToImage($article.getPathToImage());
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Shin protector recommended if amateur or pro"
salience 100
when
    $filters: Filters(sport == Sport.Fudbal, (level == SportLevel.Pro || level == SportLevel.Amater), injuries.size() == 0 )

    $article: Article()
    $shinProtector: FootballGear(type == GearTypeFootball.KostobranBezStitnika || type == GearTypeFootball.KostobranSaStitnikomZaSkocniZglob ) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Shin protector");
    recommendedArticle.setPathToImage($article.getPathToImage());
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Offer a leg warmers if shin protector was offered"
salience 10
when
    $filters: Filters(sport == Sport.Fudbal, (level == SportLevel.Pro || level == SportLevel.Amater))
    $article: Article()
    $e1: RecommendedArticleDTO()
    $shinProtector: FootballGear((type == GearTypeFootball.KostobranBezStitnika || type == GearTypeFootball.KostobranSaStitnikomZaSkocniZglob), id == $e1.getId())
    $stucne: FootballGear(type == GearTypeFootball.Stucne) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Leg warmers");
    recommendedArticle.setPathToImage($article.getPathToImage());
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Recommend sock garters if leg warmers were recommended and user is a pro"
salience 9
when
    $filters: Filters(sport == Sport.Fudbal, level == SportLevel.Pro)
    $article: Article()
    $e1: RecommendedArticleDTO(articleType == "Leg warmers")
    $podvezice: FootballGear(type == GearTypeFootball.Podvezice) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("sock garters");
    recommendedArticle.setPathToImage($article.getPathToImage());
    recommendations.add(recommendedArticle);
end

rule "Recommend shoes with 6 crampons if the player is a goalkeeper."
salience 100
when
    $filters: Filters(sport == Sport.Fudbal, typeOfFotballPlayer == SportFootballPlayer.Golman)
    $article: Article()
    $shoe: FootbalShoeCrampons(numberOfCrampons == 6) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Shoes");
    recommendedArticle.setPathToImage($article.getPathToImage());
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end