package basic;

import com.ftn.sbnz.model.Filters;
import com.ftn.sbnz.model.RecommendedArticleDTO;
import com.ftn.sbnz.model.articles.Article;
import com.ftn.sbnz.model.sport.Sport;
import com.ftn.sbnz.model.sport.SportOrientiringType;
import com.ftn.sbnz.model.articles.BigCramponOrientiringShoe;
import com.ftn.sbnz.model.articles.TypeOfOrientiringGear;
import com.ftn.sbnz.model.articles.OrientiringGear;
import com.ftn.sbnz.model.sport.SportLevel;
import com.ftn.sbnz.model.articles.Sweatpants;
import com.ftn.sbnz.model.articles.SweatpantsType;
import java.util.Set;

global Set<RecommendedArticleDTO> recommendations;

rule "Preporuci sportsku busolu ukoliko se bavi orijentiringom"
salience 100
when
    $filters: Filters(sport == Sport.Orijentiring)
    $article: Article()
    $busola: OrientiringGear(type == TypeOfOrientiringGear.Busola) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Sportska busola");
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Preporuci patike sa velikim kramponima ako se bavi orijentiringom i trka je sumska sprint"
salience 100
when
    $filters: Filters(sport == Sport.Orijentiring, typeOfRace == SportOrientiringType.SumskaSprint)
    $article: Article()
    $patike: BigCramponOrientiringShoe() from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Orientiring shoes");
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end


rule "Preporuci patike sa velikim kramponima ako se bavi orijentiringom i trka je sumska duga"
salience 100
when
    $filters: Filters(sport == Sport.Orijentiring, typeOfRace == SportOrientiringType.SumskaDuga)
    $article: Article()
    $patike: BigCramponOrientiringShoe() from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Orientiring shoes");
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Preporuci sorc ako se bavi orijentiringom i trka je gradska"
salience 100
when
    $filters: Filters(sport == Sport.Orijentiring, typeOfRace == SportOrientiringType.GradskaSprint)
    $article: Article()
    $Sweatpants: Sweatpants(type == SweatpantsType.Sorc) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Shorts");
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Preporuci poludugacke ako se bavi orijentiringom i trka je sumska dugacka"
salience 100
when
    $filters: Filters(sport == Sport.Orijentiring, typeOfRace == SportOrientiringType.SumskaDuga)
    $article: Article()
    $Sweatpants: Sweatpants(type == SweatpantsType.Poludugacko) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Half sweatpants");
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Preporuci dugacke ako se bavi orijentiringom i trka je sumska dugacka"
salience 100
when
    $filters: Filters(sport == Sport.Orijentiring, typeOfRace == SportOrientiringType.SumskaDuga)
    $article: Article()
    $Sweatpants: Sweatpants(type == SweatpantsType.Dugacko) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Sweatpants");
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Preporuci poludugacke ako se bavi orijentiringom i trka je sumska sprint"
salience 100
when
    $filters: Filters(sport == Sport.Orijentiring, typeOfRace == SportOrientiringType.SumskaSprint)
    $article: Article()
    $Sweatpants: Sweatpants(type == SweatpantsType.Poludugacko) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Half sweatpants");
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Preporuci dugacke ako se bavi orijentiringom i trka je sumska sprint"
salience 100
when
    $filters: Filters(sport == Sport.Orijentiring, typeOfRace == SportOrientiringType.SumskaSprint)
    $article: Article()
    $Sweatpants: Sweatpants(type == SweatpantsType.Dugacko) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Sweatpants");
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Preporuci kamasne ako se bavi orijentiringom i trka je sumska sprint"
salience 100
when
    $filters: Filters(sport == Sport.Orijentiring, typeOfRace == SportOrientiringType.SumskaSprint)
    $article: Article()
    $kamasne: OrientiringGear(type == TypeOfOrientiringGear.Kamasne) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Gaiters");
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Preporuci kamasne ako se bavi orijentiringom i trka je sumska duga"
salience 100
when
    $filters: Filters(sport == Sport.Orijentiring, typeOfRace == SportOrientiringType.SumskaDuga)
    $article: Article()
    $kamasne: OrientiringGear(type == TypeOfOrientiringGear.Kamasne) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Gaiters");
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Preporuci naocare za orijentiring ako se bavi orijentiringom i trka je sumska sprint"
salience 100
when
    $filters: Filters(sport == Sport.Orijentiring, typeOfRace == SportOrientiringType.SumskaSprint)
    $article: Article()
    $naocare: OrientiringGear(type == TypeOfOrientiringGear.Naocare) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Glasses");
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Preporuci naocare za orijentiring ako se bavi orijentiringom i trka je gradska sprint"
salience 100
when
    $filters: Filters(sport == Sport.Orijentiring, typeOfRace == SportOrientiringType.GradskaSprint)
    $article: Article()
    $naocare: OrientiringGear(type == TypeOfOrientiringGear.Naocare) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Glasses");
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Preporuci mu sportIdent 6-7 ukoliko se bavi profesionalno orijentiringom, ukoliko je preporucena busola i trka je sumska duga "
salience 10
when
    $filters: Filters(sport == Sport.Orijentiring, level == SportLevel.Pro,typeOfRace == SportOrientiringType.SumskaDuga )
    $article: Article()
    $e1: RecommendedArticleDTO()
    $busola: OrientiringGear(id == $e1.getId(), type== TypeOfOrientiringGear.Busola)
    $cip: OrientiringGear(type == TypeOfOrientiringGear.Cip, (name == "SportIdent 6" || name == "SportIdent 7")) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Sportski Cip");
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Preporuci mu sportIdent 8-9 ukoliko se bavi profesionalno orijentiringom, ukoliko je preporucena busola i trka je sumska sprint "
salience 10
when
    $filters: Filters(sport == Sport.Orijentiring, level == SportLevel.Pro,typeOfRace == SportOrientiringType.SumskaSprint )
    $article: Article()
    $e1: RecommendedArticleDTO()
    $busola: OrientiringGear(id == $e1.getId(), type== TypeOfOrientiringGear.Busola)
    $cip: OrientiringGear(type == TypeOfOrientiringGear.Cip, (name == "SportIdent 8" || name == "SportIdent 9")) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Sportski Cip");
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Preporuci mu sportIdent 8-9 ukoliko se bavi profesionalno orijentiringom, ukoliko je preporucena busola i trka je gradska sprint "
salience 10
when
    $filters: Filters(sport == Sport.Orijentiring, level == SportLevel.Pro,typeOfRace == SportOrientiringType.GradskaSprint )
    $article: Article()
    $e1: RecommendedArticleDTO()
    $busola: OrientiringGear(id == $e1.getId(), type== TypeOfOrientiringGear.Busola)
    $cip: OrientiringGear(type == TypeOfOrientiringGear.Cip, (name == "SportIdent 8" || name == "SportIdent 9")) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Sportski Cip");
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Preporuci mu kanap za vezivanje cipa ukoliko je preporucen Cip  i trka je sumska sprint "
salience 9
when
    $filters: Filters(typeOfRace == SportOrientiringType.SumskaSprint )
    $article: Article()
    $e1: RecommendedArticleDTO()
    $cip: OrientiringGear(id == $e1.getId(), type== TypeOfOrientiringGear.Cip)
    $kanap: OrientiringGear(type == TypeOfOrientiringGear.KanapZaCip) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Kanap za cip");
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Preporuci mu kanap za vezivanje cipa ukoliko je preporucen Cip  i trka je sumska duga "
salience 9
when
    $filters: Filters(typeOfRace == SportOrientiringType.SumskaDuga )
    $article: Article()
    $e1: RecommendedArticleDTO()
    $cip: OrientiringGear(id == $e1.getId(), type== TypeOfOrientiringGear.Cip)
    $kanap: OrientiringGear(type == TypeOfOrientiringGear.KanapZaCip) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Kanap za cip");
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end