package basic;

import com.ftn.sbnz.model.Filters;
import com.ftn.sbnz.model.RecommendedArticleDTO;
import com.ftn.sbnz.model.articles.TenisGear;
import com.ftn.sbnz.model.articles.Racket;
import com.ftn.sbnz.model.articles.TypeOfRacket;
import com.ftn.sbnz.model.articles.TypeOfRacketSpanning;
import com.ftn.sbnz.model.articles.TypeOfGear;
import com.ftn.sbnz.model.articles.TenisShoe;
import com.ftn.sbnz.model.articles.Sole;
import com.ftn.sbnz.model.articles.RacketString;
import com.ftn.sbnz.model.articles.Grip;
import com.ftn.sbnz.model.articles.Article;
import com.ftn.sbnz.model.articles.WeightliftingArticle;
import com.ftn.sbnz.model.articles.GrassFootbalShoe;
import com.ftn.sbnz.model.sport.Sport;
import com.ftn.sbnz.model.sport.SportLevel;
import com.ftn.sbnz.model.sport.SportTenisField;
import com.ftn.sbnz.model.articles.WeightliftingShoe;
import com.ftn.sbnz.model.articles.ElasticBand;
import com.ftn.sbnz.model.articles.Dumbell;
import com.ftn.sbnz.model.articles.WeightliftingGlove;
import com.ftn.sbnz.model.articles.WeightliftingGear;
import com.ftn.sbnz.model.articles.WlTypeOfGear;
import com.ftn.sbnz.model.sport.SportWeightliftingType;
import com.ftn.sbnz.model.users.Gender;
import com.ftn.sbnz.model.articles.Weight;

import java.util.Set;

global Set<RecommendedArticleDTO> recommendations;