package basic;

import com.ftn.sbnz.model.Filters;
import com.ftn.sbnz.model.RecommendedArticleDTO;
import com.ftn.sbnz.model.articles.Article;
import java.util.Set;


global Set<RecommendedArticleDTO> recommendations;


rule "GreetWhenTimeOfDayMatches"
    when
        $filters: Filters()
    then
        System.out.println("Good morning!");
end

rule "GiveBackArticle"
when
    $filters: Filters()
    $article: Article()
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendations.add(recommendedArticle);
end
