package basic;

import com.ftn.sbnz.model.Filters;
import com.ftn.sbnz.model.RecommendedArticleDTO;
import com.ftn.sbnz.model.articles.Article;
import com.ftn.sbnz.model.articles.WeightliftingArticle;
import com.ftn.sbnz.model.articles.GrassFootbalShoe;
import com.ftn.sbnz.model.sport.Sport;
import com.ftn.sbnz.model.sport.SportLevel;
import com.ftn.sbnz.model.sport.SportTenisField;
import com.ftn.sbnz.model.articles.WeightliftingShoe;
import com.ftn.sbnz.model.articles.ElasticBand;
import com.ftn.sbnz.model.articles.Dumbell;
import com.ftn.sbnz.model.articles.WeightliftingGlove;
import com.ftn.sbnz.model.articles.WeightliftingGear;
import com.ftn.sbnz.model.articles.WlTypeOfGear;
import com.ftn.sbnz.model.sport.SportWeightliftingType;
import com.ftn.sbnz.model.users.Gender;
import com.ftn.sbnz.model.articles.Weight;
import com.ftn.sbnz.model.users.Injury;

import java.util.Set;

global Set<RecommendedArticleDTO> recommendations;
global List<Injury> injuries;

rule "Recommend shoes with a hard sole"
salience 100
when
    $filters: Filters(sport == Sport.DizanjeTegova)
    $article: Article()
    $wlShoe: WeightliftingShoe() from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Weightlifting Shoes");
    recommendedArticle.setPathToImage($article.getPathToImage());
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "If they are weightlifting and under 13 years old, recommend dumbbells up to 5kg"
salience 100
when
    $filters: Filters(sport == Sport.DizanjeTegova, age < 13)
    $article: Article()
    Dumbell(weight <= 5.0) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Dumbells");
    recommendedArticle.setPathToImage($article.getPathToImage());
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "If they are weightlifting and under 13 years old, recommend resistance bands up to 15kg"
salience 100
when
    $filters: Filters(sport == Sport.DizanjeTegova, age < 13)
    $article: Article()
    ElasticBand(ebWeight <= 15.0) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Elastic Band");
    recommendedArticle.setPathToImage($article.getPathToImage());
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "If they are weightlifting, recommend weightlifting gloves"
salience 100
when
    $filters: Filters(sport == Sport.DizanjeTegova)
    $article: Article()
    WeightliftingGlove() from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Weightlifting Gloves");
    recommendedArticle.setPathToImage($article.getPathToImage());
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "If they are weightlifting and are a professional, recommend 20kg weight plates"
salience 100
when
    $filters: Filters(sport == Sport.DizanjeTegova, level == SportLevel.Pro)
    $article: Article()
    Weight(weight > 19.9) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Weight");
    recommendedArticle.setPathToImage($article.getPathToImage());
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "If they are into weightlifting and are a weightlifter or powerlifter, offer chalk as an item"
salience 100
when
    $filters: Filters(sport == Sport.DizanjeTegova, (typeOfWeightlifting == SportWeightliftingType.Weightlifting || typeOfWeightlifting == SportWeightliftingType.Powerlifting ))
    $article: Article()
    WeightliftingGear(type == WlTypeOfGear.Chalk) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Chalk");
    recommendedArticle.setPathToImage($article.getPathToImage());
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "If they are female, offer resistance bands up to 20 kg"
salience 100
when
    $filters: Filters(sport == Sport.DizanjeTegova, gender == Gender.Zensko)
    $article: Article()
    ElasticBand(ebWeight <= 20.0) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Elastic Band");
    recommendedArticle.setPathToImage($article.getPathToImage());
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "If they are male, offer resistance bands up to 60 kg"
salience 100
when
    $filters: Filters(sport == Sport.DizanjeTegova, gender == Gender.Musko)
    $article: Article()
    ElasticBand(ebWeight <= 60.0) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Elastic Band");
    recommendedArticle.setPathToImage($article.getPathToImage());
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "If they have a knee injury and are weightlifting, recommend knee wraps."
when
    Filters(sport == Sport.DizanjeTegova, $addedInjuries: injuries)
    $article: Article()
    $steznik: WeightliftingGear(type == WlTypeOfGear.KneeWrap) from $article
    Injury(name == "Povreda kolena", $injuryId: id) from injuries
    eval($addedInjuries.contains($injuryId))
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Knee Wrap");
    recommendedArticle.setPathToImage($article.getPathToImage());
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end
