package basic;

import com.ftn.sbnz.model.Filters;
import com.ftn.sbnz.model.RecommendedArticleDTO;
import com.ftn.sbnz.model.articles.Article;
import com.ftn.sbnz.model.articles.Weightlifting.WeightliftingArticle;
import com.ftn.sbnz.model.articles.Football.GrassFootbalShoe;
import com.ftn.sbnz.model.sport.Sport;
import com.ftn.sbnz.model.sport.SportLevel;
import com.ftn.sbnz.model.sport.SportTenisField;
import com.ftn.sbnz.model.articles.Weightlifting.WeightliftingShoe;
import com.ftn.sbnz.model.articles.Weightlifting.ElasticBand;
import com.ftn.sbnz.model.articles.Weightlifting.Dumbell;
import com.ftn.sbnz.model.articles.Weightlifting.WeightliftingGlove;
import com.ftn.sbnz.model.articles.Weightlifting.WeightliftingGear;
import com.ftn.sbnz.model.articles.Weightlifting.WlTypeOfGear;
import com.ftn.sbnz.model.sport.SportWeightliftingType;
import com.ftn.sbnz.model.users.Gender;

import java.util.Set;

global Set<RecommendedArticleDTO> recommendations;

rule "Preporuci patike sa tvrdim djonom"
salience 10
when
    $filters: Filters(sport == Sport.DizanjeTegova)
    $article: Article()
    $wlShoe: WeightliftingShoe() from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Weightlifting Shoes");
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Bavi se dizanjem tegova i ima manja od 13 godina, preporuci bucice do 5kg"
salience 10
when
    $filters: Filters(sport == Sport.DizanjeTegova, age < 13)
    $article: Article()
    Dumbell(weight <= 5.0) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Dumbells");
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Bavi se dizanjem tegova i ima manja od 13 godina, preporuci el. trake do 15kg"
salience 10
when
    $filters: Filters(sport == Sport.DizanjeTegova, age < 13)
    $article: Article()
    ElasticBand(ebWeight <= 15.0) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Elastic Band");
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Bavi se dizanjem tegova, preporuci rukavice za dizanje"
salience 10
when
    $filters: Filters(sport == Sport.DizanjeTegova)
    $article: Article()
    WeightliftingGlove() from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Weightlifting Gloves");
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Bavi se dizanjem tegova i weightlifter ili powerlifter je, ponudi mu krede kao artikle"
salience 10
when
    $filters: Filters(sport == Sport.DizanjeTegova, typeOfWeightlifting != SportWeightliftingType.Bodybuilding)
    $article: Article()
    WeightliftingGear(type == WlTypeOfGear.Chalk) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Chalk");
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Ukoliko je zensko, ponudi el trake do 20 kg"
salience 10
when
    $filters: Filters(sport == Sport.DizanjeTegova, gender == Gender.Zensko)
    $article: Article()
    ElasticBand(ebWeight <= 20.0) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Elastic Band");
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end

rule "Ukoliko je musko, ponudi el trake do 60 kg"
salience 10
when
    $filters: Filters(sport == Sport.DizanjeTegova, gender == Gender.Musko)
    $article: Article()
    ElasticBand(ebWeight <= 60.0) from $article
then
    RecommendedArticleDTO recommendedArticle = new RecommendedArticleDTO();
    recommendedArticle.setName($article.getName());
    recommendedArticle.setPrice($article.getPrice());
    recommendedArticle.setId($article.getId());
    recommendedArticle.setBrandName($article.getBrandName());
    recommendedArticle.setArticleType("Elastic Band");
    recommendations.add(recommendedArticle);
    insert(recommendedArticle);
end