package backward;
import com.ftn.sbnz.model.articles.Ball;
import com.ftn.sbnz.model.ClassNameBackward;
import java.util.List;

global List<String> parentClasses;

query getParent ( String x, String y )
    ClassNameBackward (x, y; )
    or
    ( ClassNameBackward(z, y;) and getParent(x,z;))
end

rule "go"
when
    String( $value: this)
    getParent($value, thing;)
then
    parentClasses.add(thing);
end
