package cep;

import com.ftn.sbnz.model.users.Injury;
import com.ftn.sbnz.model.Filters;
import com.ftn.sbnz.model.RecommendedArticleDTO;
import com.ftn.sbnz.model.articles.Article;
import com.ftn.sbnz.model.articles.GrassFootbalShoe;
import com.ftn.sbnz.model.sport.Sport;
import com.ftn.sbnz.model.sport.SportLevel;
import com.ftn.sbnz.model.sport.SportTenisField;
import com.ftn.sbnz.model.articles.Ball;
import com.ftn.sbnz.model.articles.BallType;
import com.ftn.sbnz.model.articles.GearTypeFootball;
import com.ftn.sbnz.model.articles.FootballGear;
import com.ftn.sbnz.model.articles.FootbalShoeNoCrampons;
import com.ftn.sbnz.model.sport.SportFootballType;
import com.ftn.sbnz.model.sport.SportLevel;
import com.ftn.sbnz.model.events.Purchase;
import com.ftn.sbnz.model.articles.Rating;

import java.util.Set;
import java.util.List;

global Set<RecommendedArticleDTO> recommendations;

rule "Ukoliko je kupljen neki artikal u poslednjih mesec dana, ne preporucivati ga"
salience 1000
when
    $article: RecommendedArticleDTO($id: id) from recommendations
    $purchase : Purchase(article.getId() == $id) over window:time(30d)
then
    System.out.println($article);
    recommendations.remove($article);
end

rule "Ukoliko je brend ocenjen ispod 3 5 ili vise puta u poslednjih godinu dana ne preporucuj ga"
salience 1000
when
    $article: RecommendedArticleDTO($brand: brandName) from recommendations
    Number(intValue >= 5) from accumulate(
    $rating:Rating(article.getBrandName() == $brand, rating <= 3)
    over window: time(365d),
    count($rating)
)
then
    System.out.println($article);
    recommendations.remove($article);
end